name: Comprobar archivos
on: [push]

jobs:
  archivos-grandes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Buscar archivos de mas de 1MB
        run: |
          echo "Buscando archivos grades..."
          find . -type f -size +1M -print || echo "No se encontraron archivos grandes."